<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVkj2OaM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVkj2OaM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVkj2OaM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVkj2OaM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVkj2OaM\App_KernelDevDebugContainer([
    'container.build_hash' => 'Vkj2OaM',
    'container.build_id' => '211b680b',
    'container.build_time' => 1733690975,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVkj2OaM');
