<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerRu2DHVM\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerRu2DHVM/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerRu2DHVM.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerRu2DHVM\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerRu2DHVM\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ru2DHVM',
    'container.build_id' => '4c7ad1ad',
    'container.build_time' => 1729199035,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerRu2DHVM');
