<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHAxG26u\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHAxG26u/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHAxG26u.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHAxG26u\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHAxG26u\App_KernelDevDebugContainer([
    'container.build_hash' => 'HAxG26u',
    'container.build_id' => '891a8d9a',
    'container.build_time' => 1734482439,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHAxG26u');
