<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_programme' => [[], ['_controller' => 'App\\Controller\\ProgrammeController::add'], [], [['text', '/programme/add']], [], [], []],
    'app_programme_listFull' => [[], ['_controller' => 'App\\Controller\\ProgrammeController::listFull'], [], [['text', '/programme/listfull']], [], [], []],
    'app_system' => [[], ['_controller' => 'App\\Controller\\SystemController::login'], [], [['text', '/login']], [], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], [], []],
];
